export const sidebarData = [
  {
    categoryName: "Categorias de contenido",
    categories: [
      {
        id: "image",
        name: "Imagen",
      },
      {
        id: "pdf",
        name: "PDF",
      },
      {
        id: "videoYoutube",
        name: "Video Youtube",
      },
    ],
  },
];

export const productsDataFake = [
  {
    id: "1",
    name: "Ceviched",
    image: "https://res.cloudinary.com/dqdfif7bs/image/upload/v1710357983/eyovvt44rckr7vff8dqo.jpg",
    description: "Plato emblemático a base de pescado crudo marinado en limón y especias.",
    price: 15.99,
    ingredients: ["Pescado fresco", "Limón", "Cebolla", "Cilantro", "Ají"],
    available: 1,
    deleted: 0,
    type: "platos_principales",
  },
  {
    id: "2",
    name: "Lomo Saltado",
    image: "https://res.cloudinary.com/dqdfif7bs/image/upload/v1710357983/ms3wrno1bmcxq9ozzhjy.jpg",
    description: "Salteado de carne de res con vegetales, cebolla y tomate, acompañado de papas fritas.",
    price: 18.99,
    ingredients: ["Carne de res", "Cebolla", "Tomate", "Papas", "Sillao"],
    available: 1,
    deleted: 0,
    type: "platos_principales",
  },

  {
    id: "3",
    name: "Aji de Gallina",
    image: "https://res.cloudinary.com/dqdfif7bs/image/upload/v1710357984/jpxzzmr7acpiagwtmmrp.jpg",
    description: "Estofado de pollo deshilachado en una salsa cremosa de ají amarillo.",
    price: 14.99,
    ingredients: ["Pollo", "Ají amarillo", "Leche", "Nueces", "Queso"],
    available: 1,
    deleted: 0,
    type: "platos_principales",
  },
  {
    id: "4",
    name: "Anticuchos",
    image: "https://res.cloudinary.com/dqdfif7bs/image/upload/v1710357985/mtvji7izntesthdzxfdw.jpg",
    description: "Brochetas de corazón de res marinadas y asadas a la parrilla.",
    price: 12.99,
    ingredients: ["Corazón de res", "Ajo", "Comino", "Ají panca", "Vinagre"],
    available: 1,
    deleted: 0,
    type: "platos_principales",
  },
  {
    id: "5",
    name: "Causa Rellena",
    image: "https://res.cloudinary.com/dqdfif7bs/image/upload/v1710357982/zlclhkkg9asa6gziolq6.jpg",
    description: "Capas de papa amarilla y relleno de pollo, atún o mariscos, aliñado con mayonesa y ají amarillo.",
    price: 16.99,
    ingredients: ["Papa amarilla", "Pollo", "Atún", "Mariscos", "Mayonesa"],
    available: 1,
    deleted: 0,
    type: "platos_principales",
  },
  {
    id: "6",
    name: "Rocoto Relleno",
    image: "https://res.cloudinary.com/dqdfif7bs/image/upload/v1710357984/o66f39pngph0wrlosqly.jpg",
    description: "Rocotos rellenos de carne molida, huevo duro y queso, horneados y gratinados.",
    price: 19.99,
    ingredients: ["Rocotos", "Carne molida", "Huevo duro", "Queso", "Leche"],
    available: 1,
    deleted: 0,
    type: "platos_principales",
  },
  {
    id: "7",
    name: "Ceviche",
    image: "https://res.cloudinary.com/dqdfif7bs/image/upload/v1710357983/eyovvt44rckr7vff8dqo.jpg",
    description: "Plato emblemático a base de pescado crudo marinado en limón y especias.",
    price: 15.99,
    ingredients: ["Pescado fresco", "Limón", "Cebolla", "Cilantro", "Ají"],
    available: 1,
    deleted: 0,
    type: "platos_principales",
  },
  {
    id: "8",
    name: "Lomo Saltadod",
    image: "https://res.cloudinary.com/dqdfif7bs/image/upload/v1710357983/ms3wrno1bmcxq9ozzhjy.jpg",
    description: "Salteado de carne de res con vegetales, cebolla y tomate, acompañado de papas fritas.",
    price: 18.99,
    ingredients: ["Carne de res", "Cebolla", "Tomate", "Papas", "Sillao"],
    available: 1,
    deleted: 0,
    type: "platos_principales",
  },

  {
    id: "9",
    name: "Aji de Gallinad",
    image: "https://res.cloudinary.com/dqdfif7bs/image/upload/v1710357984/jpxzzmr7acpiagwtmmrp.jpg",
    description: "Estofado de pollo deshilachado en una salsa cremosa de ají amarillo.",
    price: 14.99,
    ingredients: ["Pollo", "Ají amarillo", "Leche", "Nueces", "Queso"],
    available: 1,
    deleted: 0,
    type: "platos_principales",
  },
  {
    id: "10",
    name: "Anticuchosd",
    image: "https://res.cloudinary.com/dqdfif7bs/image/upload/v1710357985/mtvji7izntesthdzxfdw.jpg",
    description: "Brochetas de corazón de res marinadas y asadas a la parrilla.",
    price: 12.99,
    ingredients: ["Corazón de res", "Ajo", "Comino", "Ají panca", "Vinagre"],
    available: 1,
    deleted: 0,
    type: "platos_principales",
  },
  {
    id: "11",
    name: "Causa Rellenad",
    image: "https://res.cloudinary.com/dqdfif7bs/image/upload/v1710357982/zlclhkkg9asa6gziolq6.jpg",
    description: "Capas de papa amarilla y relleno de pollo, atún o mariscos, aliñado con mayonesa y ají amarillo.",
    price: 16.99,
    ingredients: ["Papa amarilla", "Pollo", "Atún", "Mariscos", "Mayonesa"],
    available: 1,
    deleted: 0,
    type: "platos_principales",
  },
  {
    id: "12",
    name: "Rocoto Rellenod",
    image: "https://res.cloudinary.com/dqdfif7bs/image/upload/v1710357984/o66f39pngph0wrlosqly.jpg",
    description: "Rocotos rellenos de carne molida, huevo duro y queso, horneados y gratinados.",
    price: 19.99,
    ingredients: ["Rocotos", "Carne molida", "Huevo duro", "Queso", "Leche"],
    available: 1,
    deleted: 0,
    type: "platos_principales",
  },
];
